# Generated by Django 4.1.7 on 2023-04-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_detail_equipe_personnel_project_user_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
