# Generated by Django 4.1.7 on 2023-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_blogpost_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Ch', 'Charte Graphique'), ('Obj', 'Objet 3D'), ('Scé', 'Scénarisation')], default='Obj', max_length=5),
        ),
    ]
