# Generated by Django 4.1.7 on 2023-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_fin',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
