# Generated by Django 4.1.7 on 2023-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0014_alter_project_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
