# Generated by Django 4.1.7 on 2023-05-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0016_project_date_debut_alter_project_date_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_debut',
        ),
    ]
