# Generated by Django 4.2.1 on 2023-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0018_remove_project_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='i',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
