# Generated by Django 4.2.1 on 2023-05-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0021_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
