# Generated by Django 4.1.7 on 2023-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0023_remove_project_i'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='catégorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='Fournisseur',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='libellé',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='file',
        ),
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
